### ISSUE TITLE
Problems at startup, most likely problems in runc

### ISSUE THREAD

**Issue by circletmate** [crafttalk/ctcli#12]
Kernel version - 3.10.0-1127.18.2.el7
OS - Fedora 7.8
trace
```bash
./runc.amd64 --root /opt/crafttalk/packaging/runc-root --debug run -b apps/filestorage filestorage
```
![image](https://user-images.githubusercontent.com/79749460/123549070-14c9a380-d770-11eb-8b95-e8d02ee58e71.png)

**Comment by dbarbashov** [comment]
https://medium.com/@Mark.io/simple-rootless-containers-with-runc-on-centos-redhat-f9230f74b88b
